name: "🧱 Improvement"
description: "Change that improves some user experience but can't be considered as a new feature"
labels:
  - "task:improvement"
assignees: []
body:
  - type: textarea
    id: context
    attributes:
      label: "Context"
      description: "Describe the context, problem, motivation of the issue. The description should answer the question:'What for? What problem, task are we solving?'"
    validations:
      required: true
  - type: textarea
    id: requirements
    attributes:
      label: "Requirements"
      description: "Describe the proposed solution or what needs to be done in a way that is convenient for you: capabilities, use cases, user stories, technical requirements, non-functional requirements"
    validations:
      required: true
  - type: textarea
    id: definition_of_done
    attributes:
      label: "Definition of Done"
      description: "A set of items that must be completed before an issue can be considered complete"
    validations:
      required: true
  - type: textarea
    id: additional_information
    attributes:
      label: "Additional Information"
      description: "Add any task context here: a link to Figma, a description of the process in Notion, Miro, other artifacts and materials"
    validations:
      required: false
  - type: textarea
    id: release_notes
    attributes:
      label: "Release notes"
      description: "Please describe what should be written about this task in the Release notes. You can use the examples below as a reference and replace the text in the brackets with details about the task"
      value: "Improved the [OpenAPI documentation] for the [Allure TestOps API]. Now [API documentation] provides [information about the most relevant path for API methods used in Allure TestOps]."
    validations:
      required: false
  - type: textarea
    id: related_tasks
    attributes:
      label: "What is included in the scope"
      description: "Specify links to related tasks: user stories, tasks, bugs and so on"
      value: |
        ```[tasklist]
        ### Related tasks
        ```
    validations:
      required: false
  - type: textarea
    id: related_feature_requests
    attributes:
      label: "Related feature requests"
      description: "Specify links to related user requests"
      placeholder: |
        - [ ] [name of feature request_1](url)
        - [ ] [name of feature request_2](url)
    validations:
      required: false
