name: "Release"
description: "Task to prepare a new release for deploying"
title: "Release {type version}"
assignees: [npolyakova, jonesnataly, vdvukhzhilov]
body:
  - type: textarea
    id: context
    attributes:
      label: "Context"
      description: "Main information about release"
      value: "Tag: https://github.com/qameta/allure-server/releases/tag/ \n
              Branch: https://github.com/qameta/allure-server/tree/release/"
  - type: textarea
    id: stages
    attributes:
      label: "Stages for testing"
      description: "Stages with the release candidate"
      value: "- [ ] Testing \n - [ ] Qatools testing"
  - type: textarea
    id: related_tasks
    attributes:
      label: "Release tasks"
      description: "Tasks we need to finish before deploying of the release"
      value: "```[tasklist] \n 
              ### Related tasks \n
              - [ ] Regression testing \n
              - [ ] Smoke testing \n
              - [ ] Release notes \n
              - [ ] Merge release to the master branch \n
              ```"