name: "👷‍♂️ Story"
description: "Description of the functionality of the software in simple and general words, compiled from the point of view of the end user"
title: "As a [person], I want [the intention]"
labels:
  - "task:story"
assignees: []
body:
  - type: textarea
    id: context
    attributes:
      label: "Context"
      description: "A summary of the user's intentions and what the product should do for him. Here you need to specify what the user wants to do and what his motivation is"
      placeholder: |
        - Format: As a [person], I want [the intention], to [user value]
        - Example: As a user role, I want to be able to enter my credentials (login and password) on the authorization page to gain access to my account
    validations:
      required: true
  - type: textarea
    id: acceptance_criteria
    attributes:
      label: "Acceptance criteria"
      description: "A set of conditions that must be met in order for the task to be considered completed"
      placeholder: |
        - When I enter the correct credentials (valid username and password), I successfully log in and go to the main page
        - When I enter incorrect credentials (invalid username or password), I get an authorization error message
        - When I click on the "Forgot Password" link, I go to the password recovery page
        - When I don't enter the required fields (login or password), I get an error message indicating the reason
    validations:
      required: false
  - type: textarea
    id: additional_information
    attributes:
      label: "Additional Information"
      description: "Add any task context here: a link to Figma, a description of the process in Notion, Miro, other artifacts and materials"
    validations:
      required: false
  - type: textarea
    id: release_notes
    attributes:
      label: "Release notes"
      description: "Please describe what should be written about this task in the Release notes. You can use the examples below as a reference and replace the text in the brackets with details about the task."
      value: "Added [‘No assignee’ option] to [filters] in the [Launches/Tree section]. Previously it was possible to [filter only by known assignee — only tests with assignee were shown]."
    validations:
      required: false
  - type: textarea
    id: related_tasks
    attributes:
      label: "What is included in the scope"
      description: "Specify links to related tasks: tasks, bugs and so on"
      value: |
        ```[tasklist]
        ### Related tasks
        ```
    validations:
      required: false
  - type: textarea
    id: related_feature_requests
    attributes:
      label: "Related feature requests"
      description: "Specify links to related user requests"
      placeholder: |
        - [ ] [name of feature request_1](url)
        - [ ] [name of feature request_2](url)
    validations:
      required: false
